---
deployment:
  tasks:
    - export APPPATH=/home/govisanc/repositories/govisan/
    - export DEPLOYPATH=/home/govisanc/public_html/
    # 1) Instalar deps y compilar
    - cd $APPPATH
    - /bin/rm -rf node_modules
    - /bin/npm ci
    - /bin/npm run build
    # 2) Publicar solo la carpeta de salida (ajusta dist/build según tu caso)
    - /bin/rsync -a --delete dist/ $DEPLOYPATH

