---
deployment:
  tasks:
    - export REPO_DIR=/home/govisanc/repositories/govisan
    - export PUBLIC_DIR=/home/govisanc/public_html

    - cd "$REPO_DIR"
    - git reset --hard
    - git clean -fd
    - git pull origin deploy

    # Copiar al docroot (sin rsync)
    - find "$PUBLIC_DIR" -mindepth 1 -maxdepth 1 ! -name 'cgi-bin' ! -name '.well-known' -exec rm -rf {} +
    - cp -a "$REPO_DIR"/. "$PUBLIC_DIR"/

    # .htaccess para SPA si no existe
    - if [ ! -f "$PUBLIC_DIR/.htaccess" ]; then echo "Options -MultiViews
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]" > "$PUBLIC_DIR/.htaccess"; fi

    # No exponer ficheros internos
    - rm -rf "$PUBLIC_DIR/.git" "$PUBLIC_DIR/.cpanel.yml" 2>/dev/null || true
