name: Build dist to deploy branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Push dist to deploy branch (content-only)
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b deploy
          git add .
          git commit -m "Deploy $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git deploy
