name: Deploy via FTPS to Govisan
on:
  push:
    branches: [ main ]   # despliega al hacer push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build   # genera dist/ (o out/ si Next export)

      - name: Deploy (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}     # 
          username: ${{ secrets.SFTP_USER }}   # 
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}       # 21 si es FTPS
          protocol: ftps
          # ==== RUTAS ====
          server-dir: /public_html/            # publica en la web principal
          local-dir: dist/                     # cambia a out/ si usas Next export
          # ==== OPCIONES ====
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
          dangerous-clean-slate: true          # borra antes de subir (cuidado)
