name: Build &  Deploy to cPanel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Ensure .htaccess in dist
        run: |
          if [ -f public/.htaccess ]; then cp public/.htaccess dist/.; fi

      # Acepta la huella del servidor para evitar el prompt interactivo
      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts
- name: Check SSH connectivity
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.CPANEL_HOST }}
    port: ${{ secrets.CPANEL_PORT }}
    username: ${{ secrets.CPANEL_USER }}
    key: ${{ secrets.CPANEL_SSH_KEY }}
    script: "echo Connected OK && uname -a"

      # (Opcional) Limpia el remoto antes de subir (¡borra todo!)
      - name: Clean remote public_html
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          port: ${{ secrets.CPANEL_PORT }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            rm -rf /home/govisanc/public_html/*

      - name: Deploy to cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          server: ${{ secrets.CPANEL_HOST }}
          port: ${{ secrets.CPANEL_PORT }}          # 22 si no tienes otro
          username: ${{ secrets.CPANEL_USER }}
          ssh_private_key: ${{ secrets.CPANEL_SSH_KEY }}  # <-- usar clave, no password
          local_path: "dist"                         # sube la carpeta completa (incluye .htaccess)
          remote_path: "/home/govisanc/public_html/"
          args: "-o StrictHostKeyChecking=no"
