name: Build & Deploy to cPanel (FTPS)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Ensure .htaccess in dist
        run: |
          if [ -f public/.htaccess ]; then cp public/.htaccess dist/.; fi

      - name: Validate FTPS secrets
        run: |
          test -n "${{ secrets.FTPS_SERVER }}"   || { echo "Falta FTPS_SERVER"; exit 1; }
          test -n "${{ secrets.FTPS_USERNAME }}" || { echo "Falta FTPS_USERNAME"; exit 1; }
          test -n "${{ secrets.FTPS_PASSWORD }}" || { echo "Falta FTPS_PASSWORD"; exit 1; }

      - name: Deploy (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          # port: ${{ secrets.FTPS_PORT }}   # opcional; si no lo pones usa 21
          local-dir: dist/                   # sube todo dist (incluye .htaccess)
          server-dir: /public_html/          # si tu FTP entra directo en public_html usa "./"
          exclude: |
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            .well-known/**                    # conserva certificados/ACME si limpias
          log-level: verbose
          # dangerous-clean-slate: true       # BORRA TODO antes de subir (úsalo solo si lo quieres)
