name: Build & Deploy to cPanel (FTPS)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Ensure .htaccess in dist
        run: |
          if [ -f public/.htaccess ]; then cp public/.htaccess dist/.; fi

 - name: Validate FTPS secrets
  run: |
    if [ -z "${{ secrets.FTPS_SERVER }}" ] || [ -z "${{ secrets.FTPS_USERNAME }}" ] || [ -z "${{ secrets.FTPS_PASSWORD }}" ]; then
      echo "Faltan secrets FTPS_SERVER / FTPS_USERNAME / FTPS_PASSWORD"; exit 1;
    fi

- name: Deploy (FTPS)
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ${{ secrets.FTPS_SERVER }}
    username: ${{ secrets.FTPS_USERNAME }}
    password: ${{ secrets.FTPS_PASSWORD }}
    protocol: ftps
    port: ${{ secrets.FTPS_PORT || 21 }}
    local-dir: dist/               # sube todo dist (incluye .htaccess)
    # OJO con el directorio remoto:
    # - si el usuario FTP entra DIRECTO en public_html -> usa "./" o "/"
    # - si entra en el home -> usa "/public_html/"
    server-dir: /public_html/
    exclude: |
      **/.git*/**
      **/node_modules/**
      **/.DS_Store
      **/Thumbs.db
    log-level: verbose
    # quita esta línea si NO quieres borrar antes:
    dangerous-clean-slate: true
