name: Build & Deploy to cPanel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Sube SOLO la carpeta de salida (ajusta dist/ o build/)
      - name: Deploy to cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          server: ${{ secrets.CPANEL_HOST }}
          port: ${{ secrets.CPANEL_PORT }} # usa 22 si no sabes
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          local_path: "dist/*"
          remote_path: "/home/govisanc/public_html/"
          delete_remote_files: true     # limpia antes de subir
          sftp_only: true
